### ISSUE TITLE
add *.net files to KiCad PCB (S-expressions) Grammar file types list

### ISSUE THREAD

**Issue by s-light** [Alhadis/language-pcb#1]
the current Nightly Builds seems to use the same S-expressions Grammar for the net-lists - so would be good to add them to the file extension list :-)

**Comment by Alhadis** [comment]
Done! 👍 Will need to think of what else to add before cutting a release though, as it seems a bit too menial to release a patch for, haha.

**Comment by s-light** [comment]
:-) thanks for adding and thanks for the language pack in the first place!! :+1: 
current 'work around' is to manually set/change the File Type..

**Comment by Alhadis** [comment]
Haha, you're welcome! I actually wrote the grammars to provide syntax highlighting across GitHub for PCB-related formats... which, uh, is the same reason I wrote (almost) every other grammar package, actually. Heh. 😜

**Comment by Alhadis** [comment]
BTW, you can add this to your user-config to add a custom filetype mapping for the new KiCad grammar:

~~~cson
"*":
	core:
		customFileTypes:
			"source.pcb.sexp": [
				"net"
			]
~~~

That's if you want `*.net` support now. =) Also, note that a leading dot isn't necessary when entering a file-extension (e.g., add `"net"`, not `".not"`... the second one will cause the rule to be ignored altogether).

More information about [custom filetypes here](http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).
